from __future__ import annotations

import os

from app.actions.base import MaintenanceAction, RegistryPlanAction, RegistryValueSpec
from app.domain.models import ActionDefinition, ActionKind, RestartRequirement, SafetyTier, Scope


def build_actions(platform) -> list:
    system_drive = os.environ.get("SystemDrive", "C:")
    program_data = os.environ.get("ProgramData", r"C:\ProgramData")
    local_app_data = os.environ.get("LocalAppData", os.environ.get("LOCALAPPDATA", r"C:\Users\Default\AppData\Local"))
    one_drive_setup = os.path.join(os.environ.get("SystemRoot", r"C:\Windows"), "SysWOW64", "OneDriveSetup.exe")
    return [
        MaintenanceAction(
            platform,
            ActionDefinition(
                id="disk_cleanup",
                title="Disk Cleanup",
                module_id="cleanup",
                legacy_label="DiskCleanup",
                description="Runs the classic Disk Cleanup utility against the system drive.",
                what_it_changes="Launches cleanmgr against the system drive.",
                why_it_may_help="Can remove stale temporary artifacts and Windows cleanup targets.",
                downside="Cleanup choices depend on Windows configuration and are not directly reversible.",
                rollback="No direct rollback. This is a one-way cleanup task.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.SAFE,
                kind=ActionKind.MAINTENANCE,
                public_group="Space Recovery",
            ),
            [["cleanmgr", "/d", system_drive]],
        ),
        MaintenanceAction(
            platform,
            ActionDefinition(
                id="clear_temp_files",
                title="Clear Temp Files",
                module_id="cleanup",
                legacy_label="ClearTempFiles",
                description="Deletes files under the current user TEMP folder.",
                what_it_changes="Removes files under the current TEMP folder.",
                why_it_may_help="Can recover space and clear stale installer debris.",
                downside="Transient files still needed by another process are not recoverable automatically.",
                rollback="No direct rollback. Deleted temp files are not recreated.",
                scope=Scope.USER,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.SAFE,
                kind=ActionKind.MAINTENANCE,
                public_group="Space Recovery",
            ),
            [["powershell", "-NoProfile", "-Command", "Remove-Item -LiteralPath $env:TEMP\\* -Force -Recurse -ErrorAction SilentlyContinue"]],
        ),
        MaintenanceAction(
            platform,
            ActionDefinition(
                id="reset_search_index",
                title="Reset Search Index",
                module_id="cleanup",
                legacy_label="ResetWindowsSearchIndex",
                description="Deletes the Search index database so Windows can rebuild it.",
                what_it_changes="Deletes Windows.edb so Search can rebuild it.",
                why_it_may_help="Useful when the index is corrupt or badly out of sync.",
                downside="Search rebuild takes time and results are temporarily incomplete.",
                rollback="No direct rollback. Windows rebuilds the index after removal.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.RESTART,
                safety_tier=SafetyTier.ADVANCED,
                kind=ActionKind.MAINTENANCE,
                public_group="Maintenance",
            ),
            [["powershell", "-NoProfile", "-Command", f"Remove-Item -LiteralPath '{program_data}\\Microsoft\\Search\\Data\\Applications\\Windows\\Windows.edb' -Force -ErrorAction SilentlyContinue"]],
        ),
        MaintenanceAction(
            platform,
            ActionDefinition(
                id="clear_browser_cache",
                title="Clear Browser Cache",
                module_id="cleanup",
                legacy_label="ClearBrowserCache",
                description="Clears the default Chrome cache directory if present.",
                what_it_changes="Removes the default Chrome cache directory.",
                why_it_may_help="Can clear corrupted or oversized browser cache files.",
                downside="Browsers need to rebuild cached assets after the next launch.",
                rollback="No direct rollback. Cache contents are re-created over time by the browser.",
                scope=Scope.USER,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.ADVANCED,
                kind=ActionKind.MAINTENANCE,
                public_group="Maintenance",
            ),
            [["powershell", "-NoProfile", "-Command", f"Remove-Item -LiteralPath '{local_app_data}\\Google\\Chrome\\User Data\\Default\\Cache' -Force -Recurse -ErrorAction SilentlyContinue"]],
        ),
        MaintenanceAction(
            platform,
            ActionDefinition(
                id="empty_recycle_bin",
                title="Empty Recycle Bin",
                module_id="cleanup",
                legacy_label="EmptyRecycleBin",
                description="Empties the current user's Recycle Bin.",
                what_it_changes="Invokes Clear-RecycleBin with force.",
                why_it_may_help="Frees disk space from already-discarded items.",
                downside="Deleted items cannot be recovered from the Recycle Bin afterward.",
                rollback="No direct rollback. Emptying the Recycle Bin is intentionally destructive.",
                scope=Scope.USER,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.ADVANCED,
                kind=ActionKind.MAINTENANCE,
                public_group="Space Recovery",
            ),
            [["powershell", "-NoProfile", "-Command", "Clear-RecycleBin -Force -ErrorAction SilentlyContinue"]],
        ),
        MaintenanceAction(
            platform,
            ActionDefinition(
                id="optimize_defrag_drives",
                title="Optimize Drives",
                module_id="cleanup",
                legacy_label="OptimizeDefragDrives",
                description="Runs Windows drive optimization on the system drive.",
                what_it_changes="Runs Windows drive optimization on the system drive.",
                why_it_may_help="Lets Windows choose TRIM or defrag behavior appropriate to the drive type.",
                downside="Takes time and should not be spammed on busy systems.",
                rollback="No direct rollback. This is a maintenance operation rather than a persistent setting.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.SAFE,
                kind=ActionKind.MAINTENANCE,
                public_group="Maintenance",
            ),
            [["defrag", system_drive, "/O"]],
        ),
        MaintenanceAction(
            platform,
            ActionDefinition(
                id="check_disk_errors",
                title="Check Disk Errors",
                module_id="cleanup",
                legacy_label="CheckDiskErrors",
                description="Runs a non-destructive online disk scan on the system drive.",
                what_it_changes="Launches chkdsk /scan against the system drive.",
                why_it_may_help="Useful when storage glitches or file-system warnings are suspected.",
                downside="Can take time and may recommend a later offline repair pass.",
                rollback="No rollback needed. This is a read-oriented maintenance scan.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.SAFE,
                kind=ActionKind.MAINTENANCE,
                public_group="Maintenance",
            ),
            [["chkdsk", system_drive, "/scan"]],
        ),
        RegistryPlanAction(
            platform,
            ActionDefinition(
                id="remove_shortcut_text",
                title="Remove Shortcut Text",
                module_id="cleanup",
                legacy_label="RemoveShortcutText",
                description="Uses the modern ShortcutNameTemplate value to suppress extra shortcut suffix text.",
                what_it_changes="Sets ShortcutNameTemplate under Explorer NamingTemplates.",
                why_it_may_help="Cleans up new shortcut names for users who prefer a minimal shell.",
                downside="Shortcut names lose the default suffix behavior that some users expect.",
                rollback="Restores the previous shortcut naming template from the snapshot.",
                scope=Scope.USER,
                restart_requirement=RestartRequirement.EXPLORER,
                safety_tier=SafetyTier.SAFE,
                public_group="Shell",
            ),
            [
                RegistryValueSpec(
                    path=r"HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\NamingTemplates",
                    name="ShortcutNameTemplate",
                    value_type="REG_SZ",
                    enabled_value="%s.lnk",
                    delete_on_disable=True,
                )
            ],
        ),
        MaintenanceAction(
            platform,
            ActionDefinition(
                id="remove_onedrive",
                title="Remove OneDrive",
                module_id="cleanup",
                legacy_label="RemoveOneDrive",
                description="Runs the bundled OneDrive uninstall entrypoint when present.",
                what_it_changes="Executes the OneDrive setup binary with /uninstall.",
                why_it_may_help="Useful for systems that do not want OneDrive installed at all.",
                downside="Uninstalls the built-in OneDrive client until it is reinstalled later.",
                rollback="No direct automatic rollback. Reinstalling OneDrive is a separate step.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.LOGOFF,
                safety_tier=SafetyTier.ADVANCED,
                kind=ActionKind.MAINTENANCE,
                public_group="Shell",
            ),
            [[one_drive_setup, "/uninstall"]],
        ),
    ]
