from __future__ import annotations

from app.actions.base import DisplayRefreshAction, NvidiaInspectorAction, RegistryPlanAction, RegistryValueSpec
from app.domain.models import ActionDefinition, RestartRequirement, SafetyTier, Scope


def build_actions(platform) -> list:
    return [
        RegistryPlanAction(
            platform,
            ActionDefinition(
                id="disable_game_dvr",
                title="Disable Game DVR",
                module_id="graphics",
                legacy_label="DisableGameDVR",
                description="Turns off the Game DVR capture stack and related policy values.",
                what_it_changes="Turns off Game DVR policy, capture, and related GameConfigStore values.",
                why_it_may_help="Avoids capture-related hooks that can interfere with gaming workflows.",
                downside="Windows capture shortcuts and some recording features stop working.",
                rollback="Restores the previous capture-related registry values from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.LOGOFF,
                safety_tier=SafetyTier.SAFE,
                public_group="Windows Graphics",
            ),
            [
                RegistryValueSpec(
                    path=r"HKLM\SOFTWARE\Microsoft\PolicyManager\default\ApplicationManagement\AllowGameDVR",
                    name="value",
                    value_type="REG_DWORD",
                    enabled_value=0,
                    disabled_value=1,
                    delete_on_disable=False,
                ),
                RegistryValueSpec(
                    path=r"HKCU\System\GameConfigStore",
                    name="GameDVR_Enabled",
                    value_type="REG_DWORD",
                    enabled_value=0,
                    disabled_value=1,
                    delete_on_disable=False,
                ),
                RegistryValueSpec(
                    path=r"HKCU\Software\Microsoft\Windows\CurrentVersion\GameDVR",
                    name="AppCaptureEnabled",
                    value_type="REG_DWORD",
                    enabled_value=0,
                    disabled_value=1,
                    delete_on_disable=False,
                ),
            ],
        ),
        RegistryPlanAction(
            platform,
            ActionDefinition(
                id="disable_hardware_gpu_scheduling",
                title="Disable Hardware GPU Scheduling",
                module_id="graphics",
                legacy_label="DisableHardwareAcceleratedGPUScheduling",
                description="Turns off hardware-accelerated GPU scheduling for troubleshooting.",
                what_it_changes="Sets HwSchMode to zero under GraphicsDrivers.",
                why_it_may_help="Useful as a troubleshooting toggle when HAGS causes instability or stutter.",
                downside="Can reduce performance on systems where HAGS works well.",
                rollback="Restores or removes the prior HwSchMode state from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.RESTART,
                safety_tier=SafetyTier.ADVANCED,
                public_group="Windows Graphics",
                min_build=19041,
            ),
            [
                RegistryValueSpec(
                    r"HKLM\SYSTEM\CurrentControlSet\Control\GraphicsDrivers",
                    "HwSchMode",
                    "REG_DWORD",
                    0,
                    disabled_value=2,
                    delete_on_disable=False,
                )
            ],
        ),
        DisplayRefreshAction(
            platform,
            ActionDefinition(
                id="set_highest_refresh_rate",
                title="Set Highest Refresh Rate",
                module_id="graphics",
                legacy_label="PreferredRefreshRate",
                description="Switches the primary display to the highest detected refresh rate.",
                what_it_changes="Changes the current display mode refresh rate on the primary display.",
                why_it_may_help="Ensures Windows is using the highest refresh rate already supported by the display.",
                downside="Some displays or cables may behave better at a lower rate.",
                rollback="Restores the previous display refresh rate from the snapshot.",
                scope=Scope.USER,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.SAFE,
                public_group="Windows Graphics",
            ),
            disabled_refresh_rate=60,
        ),
        RegistryPlanAction(
            platform,
            ActionDefinition(
                id="disable_multiplane_overlay",
                title="Disable Multiplane Overlay",
                module_id="graphics",
                legacy_label="DisableMultiplaneOverlay",
                description="Sets the DWM overlay test mode used in MPO troubleshooting.",
                what_it_changes="Writes OverlayTestMode under the DWM machine key.",
                why_it_may_help="Useful for troubleshooting flicker, black-screen flashes, or compositor instability.",
                downside="This is a graphics troubleshooting tweak, not a general performance win.",
                rollback="Restores the previous OverlayTestMode value from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.RESTART,
                safety_tier=SafetyTier.ADVANCED,
                public_group="Windows Graphics",
            ),
            [
                RegistryValueSpec(
                    path=r"HKLM\SOFTWARE\Microsoft\Windows\Dwm",
                    name="OverlayTestMode",
                    value_type="REG_DWORD",
                    enabled_value=5,
                    disabled_value=0,
                    delete_on_disable=False,
                )
            ],
        ),
        NvidiaInspectorAction(
            platform,
            ActionDefinition(
                id="nvidia_set_max_refresh_rate",
                title="NVIDIA Max Refresh Rate",
                module_id="graphics",
                legacy_label="SetMaxRefreshRate",
                description="Optional NVIDIA hook that applies the legacy preferred-refresh-rate control when the tool is available.",
                what_it_changes="Invokes nvidiaInspector.exe to set the preferred refresh-rate profile value.",
                why_it_may_help="Preserves the legacy NVIDIA-specific refresh tweak when the tool is available.",
                downside="Vendor-specific and unavailable without nvidiaInspector.exe.",
                rollback="Runs the paired NVIDIA revert command when rolling back a snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.ADVANCED,
                public_group="NVIDIA",
                requires_dependency="nvidiaInspector.exe",
            ),
            on_args=["-setPreferredRefreshRate:0"],
            off_args=["-setPreferredRefreshRate:1"],
        ),
        NvidiaInspectorAction(
            platform,
            ActionDefinition(
                id="nvidia_prefer_maximum_performance",
                title="NVIDIA Prefer Maximum Performance",
                module_id="graphics",
                legacy_label="PreferMaximumPerformance",
                description="Optional NVIDIA hook for the performance-oriented power profile.",
                what_it_changes="Invokes nvidiaInspector.exe with the legacy power-mode toggle arguments.",
                why_it_may_help="Useful for users who want the old maximum-performance NVIDIA profile hook back.",
                downside="Vendor-specific and unavailable without nvidiaInspector.exe.",
                rollback="Runs the paired NVIDIA revert command when rolling back a snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.ADVANCED,
                public_group="NVIDIA",
                requires_dependency="nvidiaInspector.exe",
            ),
            on_args=["-setPowerMizerMode:1"],
            off_args=["-setPowerMizerMode:0"],
        ),
        NvidiaInspectorAction(
            platform,
            ActionDefinition(
                id="nvidia_vertical_sync_off",
                title="NVIDIA Vertical Sync Off",
                module_id="graphics",
                legacy_label="VerticalSync",
                description="Optional NVIDIA hook for forcing V-Sync off in the vendor profile layer.",
                what_it_changes="Invokes nvidiaInspector.exe with the legacy vertical-sync arguments.",
                why_it_may_help="Useful for users reproducing the old low-latency NVIDIA profile setup.",
                downside="Vendor-specific and unavailable without nvidiaInspector.exe.",
                rollback="Runs the paired NVIDIA revert command when rolling back a snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.ADVANCED,
                public_group="NVIDIA",
                requires_dependency="nvidiaInspector.exe",
            ),
            on_args=["-setVSync:0"],
            off_args=["-setVSync:1"],
        ),
        NvidiaInspectorAction(
            platform,
            ActionDefinition(
                id="nvidia_low_latency_mode",
                title="NVIDIA Low Latency Mode",
                module_id="graphics",
                legacy_label="ZeroInputDelay",
                description="Optional NVIDIA hook for the old low-latency profile path.",
                what_it_changes="Invokes nvidiaInspector.exe with the low-latency mode arguments.",
                why_it_may_help="Preserves an NVIDIA-only low-latency profile concept when the dependency is available.",
                downside="Vendor-specific and unavailable without nvidiaInspector.exe.",
                rollback="Runs the paired NVIDIA revert command when rolling back a snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.ADVANCED,
                public_group="NVIDIA",
                requires_dependency="nvidiaInspector.exe",
            ),
            on_args=["-setLowLatencyMode:1"],
            off_args=["-setLowLatencyMode:0"],
        ),
    ]
