from __future__ import annotations

from app.actions.base import (
    EffectAction,
    RegistryEffect,
    RegistryPlanAction,
    RegistryValueSpec,
    ShellRefreshEffect,
    SystemParameterPlanAction,
)
from app.domain.models import ActionDefinition, RestartRequirement, SafetyTier, Scope


def build_actions(platform) -> list:
    return [
        SystemParameterPlanAction(
            platform,
            ActionDefinition(
                id="disable_enhance_pointer_precision",
                title="Disable Enhance Pointer Precision",
                module_id="input_ui",
                legacy_label="DisableEnhancePointerPrecision",
                description="Disables Windows pointer acceleration and applies the change immediately.",
                what_it_changes="Sets the live mouse acceleration state and mirrors the related mouse registry values.",
                why_it_may_help="Produces more predictable raw-feeling pointer behavior for gaming.",
                downside="Users who prefer Windows acceleration may dislike the change.",
                rollback="Restores the previous mouse acceleration state from the snapshot.",
                scope=Scope.USER,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.SAFE,
                public_group="Mouse",
            ),
            name="enhance_pointer_precision",
            enabled_value=False,
            disabled_value=True,
            broadcast_key="mouse",
            extra_effects=[
                RegistryEffect(
                    platform,
                    RegistryValueSpec(r"HKCU\Control Panel\Mouse", "MouseThreshold1", "REG_SZ", "0", disabled_value="6", delete_on_disable=False),
                ),
                RegistryEffect(
                    platform,
                    RegistryValueSpec(r"HKCU\Control Panel\Mouse", "MouseThreshold2", "REG_SZ", "0", disabled_value="10", delete_on_disable=False),
                ),
                RegistryEffect(
                    platform,
                    RegistryValueSpec(r"HKCU\Control Panel\Mouse", "MouseSpeed", "REG_SZ", "0", disabled_value="1", delete_on_disable=False),
                ),
            ],
        ),
        SystemParameterPlanAction(
            platform,
            ActionDefinition(
                id="adjust_mouse_trails",
                title="Adjust Mouse Trails",
                module_id="input_ui",
                legacy_label="AdjustMouseTrails",
                description="Turns on a moderate mouse trail for high-visibility cursor setups.",
                what_it_changes="Sets the live mouse-trails count and mirrors it in the current-user mouse settings.",
                why_it_may_help="Can improve cursor visibility on specific displays or capture setups.",
                downside="Adds a visible trail effect that many users will not want permanently.",
                rollback="Restores the previous MouseTrails value from the snapshot.",
                scope=Scope.USER,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.SAFE,
                public_group="Mouse",
            ),
            name="mouse_trails",
            enabled_value=5,
            disabled_value=0,
            broadcast_key="mouse",
        ),
        SystemParameterPlanAction(
            platform,
            ActionDefinition(
                id="optimize_mouse_double_click",
                title="Optimize Mouse Double-Click",
                module_id="input_ui",
                legacy_label="OptimizeMouseDoubleClick",
                description="Lowers the double-click time to a faster response window.",
                what_it_changes="Sets the live DoubleClickTime and mirrors it in the current-user mouse settings.",
                why_it_may_help="Improves responsiveness for users who prefer quick click recognition.",
                downside="Can make accidental double-clicks more likely.",
                rollback="Restores the previous DoubleClickSpeed from the snapshot.",
                scope=Scope.USER,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.SAFE,
                public_group="Mouse",
            ),
            name="double_click_speed",
            enabled_value=200,
            disabled_value=500,
            broadcast_key="mouse",
        ),
        RegistryPlanAction(
            platform,
            ActionDefinition(
                id="optimize_keyboard_buffer",
                title="Optimize Keyboard Buffer",
                module_id="input_ui",
                legacy_label="OptimizeKeyboardBuffer",
                description="Applies the old keyboard buffer size tweak.",
                what_it_changes="Sets KeyboardBufferSize for the current user.",
                why_it_may_help="Preserves the original input-focused behavior reference.",
                downside="Windows may ignore the setting on newer builds and the benefit is modest.",
                rollback="Restores the previous KeyboardBufferSize from the snapshot.",
                scope=Scope.USER,
                restart_requirement=RestartRequirement.LOGOFF,
                safety_tier=SafetyTier.ADVANCED,
                public_group="Keyboard",
            ),
            [
                RegistryValueSpec(r"HKCU\Control Panel\Keyboard", "KeyboardBufferSize", "REG_SZ", "100"),
            ],
        ),
        SystemParameterPlanAction(
            platform,
            ActionDefinition(
                id="optimize_key_repeat_delay",
                title="Optimize Key Repeat Delay",
                module_id="input_ui",
                legacy_label="OptimizeKeyRepeatDelay",
                description="Reduces the keyboard repeat delay to its fastest setting.",
                what_it_changes="Sets the live keyboard repeat delay and mirrors it in the current-user keyboard settings.",
                why_it_may_help="Improves perceived keyboard responsiveness in some games and desktop workflows.",
                downside="Can feel too aggressive for typists who prefer a slower repeat delay.",
                rollback="Restores the previous KeyDelay from the snapshot.",
                scope=Scope.USER,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.SAFE,
                public_group="Keyboard",
            ),
            name="key_delay",
            enabled_value=0,
            disabled_value=1,
            broadcast_key="keyboard",
        ),
        EffectAction(
            platform,
            ActionDefinition(
                id="disable_recent_files",
                title="Disable Recent Files",
                module_id="input_ui",
                legacy_label="DisableRecentFiles",
                description="Turns off recent-document tracking in Explorer surfaces.",
                what_it_changes="Sets Start_TrackDocs to zero in Explorer advanced settings.",
                why_it_may_help="Keeps shell recommendations quieter and reduces recent-item tracking.",
                downside="Recent documents stop surfacing in shell surfaces that rely on them.",
                rollback="Restores the previous Start_TrackDocs value from the snapshot.",
                scope=Scope.USER,
                restart_requirement=RestartRequirement.EXPLORER,
                safety_tier=SafetyTier.SAFE,
                public_group="Shell",
            ),
            [
                RegistryEffect(
                    platform,
                    RegistryValueSpec(
                        r"HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
                        "Start_TrackDocs",
                        "REG_DWORD",
                        0,
                        disabled_value=1,
                        delete_on_disable=False,
                    ),
                ),
                ShellRefreshEffect(platform, refresh_explorer=True),
            ],
        ),
        EffectAction(
            platform,
            ActionDefinition(
                id="disable_widgets",
                title="Disable Widgets",
                module_id="input_ui",
                legacy_label="DisableWidgets",
                description="Removes the Windows widgets surface from the taskbar experience.",
                what_it_changes="Sets ShellFeedsTaskbarViewMode to zero and refreshes Explorer.",
                why_it_may_help="Removes a background widget surface and its taskbar presence.",
                downside="Widgets and feed-style taskbar content stop appearing.",
                rollback="Restores the previous feeds taskbar mode from the snapshot.",
                scope=Scope.USER,
                restart_requirement=RestartRequirement.EXPLORER,
                safety_tier=SafetyTier.SAFE,
                public_group="Shell",
            ),
            [
                RegistryEffect(
                    platform,
                    RegistryValueSpec(
                        r"HKCU\Software\Microsoft\Windows\CurrentVersion\Feeds",
                        "ShellFeedsTaskbarViewMode",
                        "REG_DWORD",
                        0,
                        disabled_value=1,
                        delete_on_disable=False,
                    ),
                ),
                ShellRefreshEffect(platform, refresh_explorer=True),
            ],
        ),
        EffectAction(
            platform,
            ActionDefinition(
                id="disable_animations",
                title="Disable Animations",
                module_id="input_ui",
                legacy_label="DisableAnimations",
                description="Turns off taskbar and window animations for a snappier desktop feel.",
                what_it_changes="Sets TaskbarAnimations and MinAnimate to zero and refreshes the shell.",
                why_it_may_help="Makes the shell feel faster and more immediate.",
                downside="The desktop feels less polished and less animated.",
                rollback="Restores the previous animation settings from the snapshot.",
                scope=Scope.USER,
                restart_requirement=RestartRequirement.EXPLORER,
                safety_tier=SafetyTier.SAFE,
                public_group="Desktop",
            ),
            [
                RegistryEffect(
                    platform,
                    RegistryValueSpec(
                        r"HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
                        "TaskbarAnimations",
                        "REG_DWORD",
                        0,
                        disabled_value=1,
                        delete_on_disable=False,
                    ),
                ),
                RegistryEffect(
                    platform,
                    RegistryValueSpec(
                        r"HKCU\Control Panel\Desktop\WindowMetrics",
                        "MinAnimate",
                        "REG_SZ",
                        "0",
                        disabled_value="1",
                        delete_on_disable=False,
                    ),
                ),
                ShellRefreshEffect(platform, refresh_explorer=True),
            ],
        ),
        EffectAction(
            platform,
            ActionDefinition(
                id="disable_aero_peak",
                title="Disable Aero Peek",
                module_id="input_ui",
                legacy_label="DisableAeroPeak",
                description="Turns off Aero Peek previews in the desktop compositor settings.",
                what_it_changes="Sets EnableAeroPeek to zero under the DWM current-user key.",
                why_it_may_help="Removes a desktop-preview behavior some users never use.",
                downside="Taskbar peek previews stop working.",
                rollback="Restores the previous Aero Peek setting from the snapshot.",
                scope=Scope.USER,
                restart_requirement=RestartRequirement.EXPLORER,
                safety_tier=SafetyTier.SAFE,
                public_group="Desktop",
            ),
            [
                RegistryEffect(
                    platform,
                    RegistryValueSpec(
                        r"HKCU\Software\Microsoft\Windows\DWM",
                        "EnableAeroPeek",
                        "REG_DWORD",
                        0,
                        disabled_value=1,
                        delete_on_disable=False,
                    ),
                ),
                ShellRefreshEffect(platform, refresh_explorer=True),
            ],
        ),
        EffectAction(
            platform,
            ActionDefinition(
                id="disable_balloon_tips",
                title="Disable Balloon Tips",
                module_id="input_ui",
                legacy_label="DisableBalloonTips",
                description="Disables legacy Explorer balloon-tip notifications.",
                what_it_changes="Sets EnableBalloonTips to zero under Explorer advanced settings.",
                why_it_may_help="Keeps the shell quieter for users who do not want tip popups.",
                downside="Helpful balloon-style Explorer tips stop appearing.",
                rollback="Restores the previous balloon-tip setting from the snapshot.",
                scope=Scope.USER,
                restart_requirement=RestartRequirement.EXPLORER,
                safety_tier=SafetyTier.SAFE,
                public_group="Desktop",
            ),
            [
                RegistryEffect(
                    platform,
                    RegistryValueSpec(
                        r"HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
                        "EnableBalloonTips",
                        "REG_DWORD",
                        0,
                        disabled_value=1,
                        delete_on_disable=False,
                    ),
                ),
                ShellRefreshEffect(platform, refresh_explorer=True),
            ],
        ),
        EffectAction(
            platform,
            ActionDefinition(
                id="improve_menu_speed",
                title="Improve Menu Speed",
                module_id="input_ui",
                legacy_label="ImproveMenuSpeed",
                description="Reduces the shell menu show delay to a faster, still-readable value.",
                what_it_changes="Sets MenuShowDelay to 20 milliseconds and refreshes the shell.",
                why_it_may_help="Makes menus feel more responsive without going fully instant.",
                downside="Users who prefer slower menu animation timing may dislike it.",
                rollback="Restores the previous MenuShowDelay value from the snapshot.",
                scope=Scope.USER,
                restart_requirement=RestartRequirement.EXPLORER,
                safety_tier=SafetyTier.SAFE,
                public_group="Desktop",
            ),
            [
                RegistryEffect(
                    platform,
                    RegistryValueSpec(
                        r"HKCU\Control Panel\Desktop",
                        "MenuShowDelay",
                        "REG_SZ",
                        "20",
                        disabled_value="400",
                        delete_on_disable=False,
                    ),
                ),
                ShellRefreshEffect(platform, refresh_explorer=True),
            ],
        ),
    ]
