from __future__ import annotations

from app.actions.base import (
    CompositeInterfaceRegistryAction,
    CompositeTcpAction,
    NetAdapterFeatureAction,
    RegistryPlanAction,
    RegistryValueSpec,
    ServicePlanAction,
    TcpGlobalAction,
)
from app.domain.models import ActionDefinition, RestartRequirement, SafetyTier, Scope


def build_actions(platform) -> list:
    return [
        TcpGlobalAction(
            platform,
            ActionDefinition(
                id="disable_auto_tuning",
                title="Disable Auto-Tuning",
                module_id="network",
                legacy_label="DisableAutoTuning",
                description="Turns off TCP receive-window auto-tuning.",
                what_it_changes="Sets the TCP autotuninglevel global policy through netsh.",
                why_it_may_help="Can reduce latency spikes on problem networks.",
                downside="Can reduce throughput on high-latency connections.",
                rollback="Restores the previous TCP global auto-tuning state from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.ADVANCED,
                public_group="TCP",
            ),
            key="autotuninglevel",
            enabled_value="disabled",
            disabled_value="normal",
        ),
        CompositeInterfaceRegistryAction(
            platform,
            ActionDefinition(
                id="disable_nagle_algorithm",
                title="Disable Nagle Algorithm",
                module_id="network",
                legacy_label="DisableNagleAlgorithm",
                description="Applies the classic low-latency TCPNoDelay and TcpAckFrequency combination.",
                what_it_changes="Sets TcpAckFrequency and TCPNoDelay on the TCP interface registry keys.",
                why_it_may_help="Can reduce packet coalescing latency for games and input-sensitive traffic.",
                downside="May increase packet overhead on slower or congested links.",
                rollback="Restores the previous interface registry values from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.RESTART,
                safety_tier=SafetyTier.ADVANCED,
                public_group="TCP",
            ),
            specs=[
                {"value_name": "TcpAckFrequency", "enabled_value": 1},
                {"value_name": "TCPNoDelay", "enabled_value": 1},
            ],
        ),
        CompositeInterfaceRegistryAction(
            platform,
            ActionDefinition(
                id="optimize_tcp_ack_frequency",
                title="Optimize TCP Ack Frequency",
                module_id="network",
                legacy_label="OptimizeTCPAckFrequency",
                description="Reduces delayed ACK timing on interface keys.",
                what_it_changes="Sets TCPDelAckTicks to zero on active TCP interfaces.",
                why_it_may_help="May lower perceived network delay in latency-sensitive sessions.",
                downside="Not all adapters or stacks benefit from reduced delayed ACK timing.",
                rollback="Restores the previous TCPDelAckTicks values from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.RESTART,
                safety_tier=SafetyTier.ADVANCED,
                public_group="TCP",
            ),
            specs=[
                {"value_name": "TCPDelAckTicks", "enabled_value": 0},
            ],
        ),
        RegistryPlanAction(
            platform,
            ActionDefinition(
                id="disable_llmnr",
                title="Disable LLMNR",
                module_id="network",
                legacy_label="DisableLLMNR",
                description="Turns off Link-Local Multicast Name Resolution.",
                what_it_changes="Sets EnableMulticast to zero in the DNS client policy key.",
                why_it_may_help="Reduces unnecessary multicast name-resolution traffic on managed networks.",
                downside="Link-local name fallback becomes less permissive on small unmanaged networks.",
                rollback="Restores the previous LLMNR policy state from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.RESTART,
                safety_tier=SafetyTier.SAFE,
                public_group="Resolution",
            ),
            [
                RegistryValueSpec(
                    path=r"HKLM\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient",
                    name="EnableMulticast",
                    value_type="REG_DWORD",
                    enabled_value=0,
                    disabled_value=1,
                    delete_on_disable=False,
                )
            ],
        ),
        RegistryPlanAction(
            platform,
            ActionDefinition(
                id="adjust_dns_cache",
                title="Adjust DNS Cache",
                module_id="network",
                legacy_label="AdjustDNSCache",
                description="Applies conservative DNS cache tuning values.",
                what_it_changes="Sets MaxCacheTtl and MaxNegativeCacheTtl under the Dnscache parameters key.",
                why_it_may_help="Can reduce stale negative-cache behavior and keep DNS caching predictable.",
                downside="This is an advanced cache policy tweak with modest upside on many systems.",
                rollback="Restores the prior DNS cache parameter values from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.RESTART,
                safety_tier=SafetyTier.ADVANCED,
                public_group="Resolution",
            ),
            [
                RegistryValueSpec(
                    path=r"HKLM\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters",
                    name="MaxCacheTtl",
                    value_type="REG_DWORD",
                    enabled_value=86400,
                    disabled_value=172800,
                    delete_on_disable=False,
                ),
                RegistryValueSpec(
                    path=r"HKLM\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters",
                    name="MaxNegativeCacheTtl",
                    value_type="REG_DWORD",
                    enabled_value=0,
                    disabled_value=300,
                    delete_on_disable=False,
                ),
            ],
        ),
        ServicePlanAction(
            platform,
            ActionDefinition(
                id="disable_bits",
                title="Disable BITS",
                module_id="network",
                legacy_label="DisableBITS",
                description="Disables the Background Intelligent Transfer Service.",
                what_it_changes="Sets BITS to Disabled and stops the service.",
                why_it_may_help="Useful only for troubleshooting or short-lived benchmark sessions.",
                downside="Windows Update and other software can depend on BITS transfers.",
                rollback="Restores the previous BITS startup state from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.ADVANCED,
                public_group="Services",
            ),
            services=["BITS"],
        ),
        RegistryPlanAction(
            platform,
            ActionDefinition(
                id="disable_qos",
                title="Reduce QoS Reservation",
                module_id="network",
                legacy_label="DisableQoS",
                description="Sets the NonBestEffortLimit policy to zero reserved bandwidth.",
                what_it_changes="Writes NonBestEffortLimit under the Windows Psched policy key.",
                why_it_may_help="Useful for users who want explicit control over the Windows reserved-bandwidth policy.",
                downside="The practical benefit is often small and workload-dependent.",
                rollback="Restores the previous NonBestEffortLimit policy from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.RESTART,
                safety_tier=SafetyTier.ADVANCED,
                public_group="Services",
            ),
            [
                RegistryValueSpec(
                    path=r"HKLM\SOFTWARE\Policies\Microsoft\Windows\Psched",
                    name="NonBestEffortLimit",
                    value_type="REG_DWORD",
                    enabled_value=0,
                    disabled_value=20,
                    delete_on_disable=False,
                )
            ],
        ),
        RegistryPlanAction(
            platform,
            ActionDefinition(
                id="disable_ipv6",
                title="Disable IPv6",
                module_id="network",
                legacy_label="DisableIPv6",
                description="Applies the Windows DisabledComponents mask that suppresses IPv6.",
                what_it_changes="Sets DisabledComponents under the Tcpip6 parameters key.",
                why_it_may_help="Useful only when specifically troubleshooting IPv6-related stack issues.",
                downside="Can break services or apps that expect IPv6 to remain available.",
                rollback="Restores the previous DisabledComponents state from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.RESTART,
                safety_tier=SafetyTier.EXPERIMENTAL,
                public_group="Adapters",
            ),
            [
                RegistryValueSpec(
                    path=r"HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters",
                    name="DisabledComponents",
                    value_type="REG_DWORD",
                    enabled_value=255,
                    disabled_value=0,
                    delete_on_disable=False,
                )
            ],
        ),
        NetAdapterFeatureAction(
            platform,
            ActionDefinition(
                id="disable_lso",
                title="Disable Large Send Offload",
                module_id="network",
                legacy_label="DisableLSO",
                description="Turns off Large Send Offload on supported adapters.",
                what_it_changes="Uses the NetAdapter LSO controls for IPv4 and IPv6 capable adapters.",
                why_it_may_help="Useful when adapter offload behavior is suspected to cause latency or stability problems.",
                downside="Can increase CPU cost on systems where offload works well.",
                rollback="Restores the previous LSO enabled state from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.ADVANCED,
                public_group="Adapters",
            ),
            feature="lso",
            enabled_value=False,
            disabled_value=True,
        ),
        RegistryPlanAction(
            platform,
            ActionDefinition(
                id="disable_background_scans",
                title="Disable Background Scans",
                module_id="network",
                legacy_label="DisableBackgroundScans",
                description="Disables idle SMB background scans on workstation and server service parameters.",
                what_it_changes="Sets DisableIdleScan on the lanmanserver and lanmanworkstation parameter keys.",
                why_it_may_help="Reduces SMB-side background scanning overhead on some systems.",
                downside="Could reduce automatic network-share background maintenance behavior.",
                rollback="Restores the previous lanman DisableIdleScan values from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.RESTART,
                safety_tier=SafetyTier.ADVANCED,
                public_group="Services",
            ),
            [
                RegistryValueSpec(
                    path=r"HKLM\SYSTEM\CurrentControlSet\Services\lanmanserver\parameters",
                    name="DisableIdleScan",
                    value_type="REG_DWORD",
                    enabled_value=1,
                    disabled_value=0,
                    delete_on_disable=False,
                ),
                RegistryValueSpec(
                    path=r"HKLM\SYSTEM\CurrentControlSet\Services\lanmanworkstation\parameters",
                    name="DisableIdleScan",
                    value_type="REG_DWORD",
                    enabled_value=1,
                    disabled_value=0,
                    delete_on_disable=False,
                ),
            ],
        ),
        CompositeTcpAction(
            platform,
            ActionDefinition(
                id="optimize_network_services",
                title="Optimize Network Services",
                module_id="network",
                legacy_label="OptimizeNetworkServices",
                description="Tunes TCP heuristics, DCA, and RSS as a grouped network-service action.",
                what_it_changes="Disables TCP heuristics and enables DCA and RSS where the stack supports them.",
                why_it_may_help="Can reduce conservative TCP behavior and improve packet handling on some systems.",
                downside="Benefit varies by NIC driver quality and Windows build.",
                rollback="Restores the previous TCP heuristics, DCA, and RSS values from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.ADVANCED,
                public_group="Services",
            ),
            enabled_values={"heuristics": "disabled", "dca": "enabled", "rss": "enabled"},
            disabled_values={"heuristics": "enabled", "dca": "disabled", "rss": "enabled"},
        ),
    ]
