from __future__ import annotations

from app.actions.base import RegistryPlanAction, RegistryValueSpec, ServicePlanAction
from app.domain.models import ActionDefinition, RestartRequirement, SafetyTier, Scope


def build_actions(platform) -> list:
    return [
        RegistryPlanAction(
            platform,
            ActionDefinition(
                id="disable_telemetry",
                title="Disable Telemetry",
                module_id="services",
                legacy_label="DisableTelemetry",
                description="Turns off the primary Windows telemetry policy value.",
                what_it_changes="Writes AllowTelemetry=0 under the Windows DataCollection policy key.",
                why_it_may_help="Reduces a noisy background diagnostic channel from the original tool.",
                downside="Can reduce diagnostic detail available to Microsoft troubleshooting flows.",
                rollback="Restores the previous AllowTelemetry policy value from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.RESTART,
                safety_tier=SafetyTier.SAFE,
                public_group="Privacy",
            ),
            [
                RegistryValueSpec(
                    path=r"HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection",
                    name="AllowTelemetry",
                    value_type="REG_DWORD",
                    enabled_value=0,
                    disabled_value=3,
                    delete_on_disable=False,
                )
            ],
        ),
        RegistryPlanAction(
            platform,
            ActionDefinition(
                id="disable_background_apps",
                title="Disable Background Apps",
                module_id="services",
                legacy_label="DisableBackgroundApps",
                description="Restricts background app execution for the current user.",
                what_it_changes="Sets GlobalUserDisabled and ContentDeliveryAllowed for the current user.",
                why_it_may_help="Reduces background app wakeups and recommendation churn.",
                downside="Some apps may stop refreshing until you open them directly.",
                rollback="Restores the previous background access and content-delivery settings from the snapshot.",
                scope=Scope.USER,
                restart_requirement=RestartRequirement.LOGOFF,
                safety_tier=SafetyTier.SAFE,
                public_group="Privacy",
            ),
            [
                RegistryValueSpec(
                    path=r"HKCU\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications",
                    name="GlobalUserDisabled",
                    value_type="REG_DWORD",
                    enabled_value=1,
                    disabled_value=0,
                    delete_on_disable=False,
                ),
                RegistryValueSpec(
                    path=r"HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager",
                    name="ContentDeliveryAllowed",
                    value_type="REG_DWORD",
                    enabled_value=0,
                    disabled_value=1,
                    delete_on_disable=False,
                ),
            ],
        ),
        RegistryPlanAction(
            platform,
            ActionDefinition(
                id="disable_cortana",
                title="Disable Cortana Web Search",
                module_id="services",
                legacy_label="DisableCortana",
                description="Reduces web-backed search behavior and the older Cortana policy surface.",
                what_it_changes="Turns off AllowCortana, BingSearchEnabled, and AllowSearchToUseLocation.",
                why_it_may_help="Reduces web-backed search behavior and some search assistant features.",
                downside="Search results can become less rich or less contextual.",
                rollback="Restores the previous search policy values from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.LOGOFF,
                safety_tier=SafetyTier.SAFE,
                public_group="Privacy",
            ),
            [
                RegistryValueSpec(
                    path=r"HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search",
                    name="AllowCortana",
                    value_type="REG_DWORD",
                    enabled_value=0,
                    disabled_value=1,
                    delete_on_disable=False,
                ),
                RegistryValueSpec(
                    path=r"HKCU\Software\Microsoft\Windows\CurrentVersion\Search",
                    name="BingSearchEnabled",
                    value_type="REG_DWORD",
                    enabled_value=0,
                    disabled_value=1,
                    delete_on_disable=False,
                ),
                RegistryValueSpec(
                    path=r"HKCU\Software\Microsoft\Windows\CurrentVersion\Search",
                    name="AllowSearchToUseLocation",
                    value_type="REG_DWORD",
                    enabled_value=0,
                    disabled_value=1,
                    delete_on_disable=False,
                ),
            ],
        ),
        ServicePlanAction(
            platform,
            ActionDefinition(
                id="disable_xbox_services",
                title="Disable Xbox Services",
                module_id="services",
                legacy_label="DisableXboxServices",
                description="Disables the core Xbox background services used by sign-in and cloud saves.",
                what_it_changes="Sets XblAuthManager and XblGameSave to Disabled and stops them.",
                why_it_may_help="Cuts background Xbox-related service activity on machines that do not use it.",
                downside="Xbox sign-in, cloud sync, and some game integrations may stop working.",
                rollback="Restores the previous Xbox service startup states from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.ADVANCED,
                public_group="Gaming",
            ),
            services=["XblAuthManager", "XblGameSave"],
        ),
        ServicePlanAction(
            platform,
            ActionDefinition(
                id="disable_bluetooth",
                title="Disable Bluetooth",
                module_id="services",
                legacy_label="DisableBluetooth",
                description="Disables the Bluetooth Support Service on systems that do not need Bluetooth.",
                what_it_changes="Sets the Bluetooth support service to Disabled and stops it.",
                why_it_may_help="Cuts background Bluetooth service activity on systems that never use Bluetooth.",
                downside="Bluetooth peripherals stop working until you re-enable the service.",
                rollback="Restores the previous Bluetooth service state from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.ADVANCED,
                public_group="Hardware",
            ),
            services=["bthserv"],
        ),
        RegistryPlanAction(
            platform,
            ActionDefinition(
                id="disable_notifications",
                title="Disable Notifications",
                module_id="services",
                legacy_label="DisableNotifications",
                description="Turns off toast notifications for the current user.",
                what_it_changes="Sets ToastEnabled to zero in PushNotifications settings.",
                why_it_may_help="Reduces interruptions and background notification surfaces.",
                downside="App and system toast notifications stop appearing.",
                rollback="Restores the previous toast-notification setting from the snapshot.",
                scope=Scope.USER,
                restart_requirement=RestartRequirement.LOGOFF,
                safety_tier=SafetyTier.SAFE,
                public_group="Notifications",
            ),
            [
                RegistryValueSpec(
                    path=r"HKCU\Software\Microsoft\Windows\CurrentVersion\PushNotifications",
                    name="ToastEnabled",
                    value_type="REG_DWORD",
                    enabled_value=0,
                    disabled_value=1,
                    delete_on_disable=False,
                )
            ],
        ),
        ServicePlanAction(
            platform,
            ActionDefinition(
                id="disable_diagnostic_tracking",
                title="Disable Diagnostic Tracking",
                module_id="services",
                legacy_label="DisableDiagnostic",
                description="Disables the DiagTrack service behind several Windows diagnostic collection flows.",
                what_it_changes="Sets the Diagnostic Tracking Service to Disabled and stops it.",
                why_it_may_help="Reduces background diagnostic collection activity beyond the top-level telemetry policy.",
                downside="Additional diagnostic and feedback collection paths stop running.",
                rollback="Restores the prior DiagTrack service state from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.NONE,
                safety_tier=SafetyTier.ADVANCED,
                public_group="Privacy",
            ),
            services=["DiagTrack"],
        ),
        RegistryPlanAction(
            platform,
            ActionDefinition(
                id="disable_smartscreen",
                title="Disable SmartScreen",
                module_id="services",
                legacy_label="DisableSmartScreen",
                description="Turns off Windows SmartScreen policy values.",
                what_it_changes="Sets EnableSmartScreen to zero under the Windows System policy key.",
                why_it_may_help="Only useful for niche compatibility cases where SmartScreen gets in the way.",
                downside="Reduces reputation-based download and application protection.",
                rollback="Restores the previous SmartScreen policy state from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.RESTART,
                safety_tier=SafetyTier.ADVANCED,
                public_group="Security",
            ),
            [
                RegistryValueSpec(
                    path=r"HKLM\SOFTWARE\Policies\Microsoft\Windows\System",
                    name="EnableSmartScreen",
                    value_type="REG_DWORD",
                    enabled_value=0,
                    disabled_value=1,
                    delete_on_disable=False,
                )
            ],
        ),
        RegistryPlanAction(
            platform,
            ActionDefinition(
                id="disable_uac",
                title="Disable UAC",
                module_id="services",
                legacy_label="DisableUAC",
                description="Turns off the main UAC EnableLUA switch.",
                what_it_changes="Sets EnableLUA to zero under the Windows system policy key.",
                why_it_may_help="Useful only for niche compatibility or benchmark scenarios.",
                downside="Significantly reduces core Windows security protections and requires a reboot.",
                rollback="Restores the previous EnableLUA state from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.RESTART,
                safety_tier=SafetyTier.EXPERIMENTAL,
                public_group="Security",
            ),
            [
                RegistryValueSpec(
                    path=r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
                    name="EnableLUA",
                    value_type="REG_DWORD",
                    enabled_value=0,
                    disabled_value=1,
                    delete_on_disable=False,
                )
            ],
        ),
        RegistryPlanAction(
            platform,
            ActionDefinition(
                id="disable_error_reporting",
                title="Disable Error Reporting",
                module_id="services",
                legacy_label="DisableErrorReporting",
                description="Turns off Windows Error Reporting policy collection.",
                what_it_changes="Sets Disabled to one under the Windows Error Reporting policy key.",
                why_it_may_help="Reduces one more background reporting path on tuned systems.",
                downside="Crash reporting and related troubleshooting feedback become less available.",
                rollback="Restores the previous Windows Error Reporting policy state from the snapshot.",
                scope=Scope.MACHINE,
                restart_requirement=RestartRequirement.RESTART,
                safety_tier=SafetyTier.ADVANCED,
                public_group="Privacy",
            ),
            [
                RegistryValueSpec(
                    path=r"HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting",
                    name="Disabled",
                    value_type="REG_DWORD",
                    enabled_value=1,
                    disabled_value=0,
                    delete_on_disable=False,
                )
            ],
        ),
    ]
